.\"
.\" (c) copyright 1999-2002 by wojtek kaniewski <wojtekka@dev.null.pl>
.\" $Id$
.\"
.TH BPSET 8 "May 8, 2002"
.SH NAME
bpset \- manage bindprivs rules
.SH SYNOPSIS
.B bpset
[\-sflu] [\-\-set] [\-\-flush] [\-\-list] [\-\-unload] [\-\-help] [\-\-version] [filename]
.SH DESCRIPTION
.B bpset
allows you to manage access rules used by
.B bindprivs
kernel module and the module itself.
.SH OPTIONS
.TP
.B "\-s, \-\-set [filename]"
Load rules from specified file. If filename is ommited, the default
/etc/bindprivs.conf file is loaded.
.TP
.B "\-f, \-\-flush"
Flush rules.
.TP
.B "\-u, \-\-unload"
Prepare the module for 
.BR rmmod(8) ". "
You should wait until the module is unused, before actually removing it
from the memory.
.TP
.B "\-l, \-\-list"
List rules.
.TP
.B "\-h, \-\-help"
Print a usage message and exit.
.TP
.B "\-V, \-\-version"
Print program version and exit.
.SH AUTHOR
Wojtek Kaniewski (wojtekka@dev.null.pl)
.SH "SEE ALSO"
.BR bind "(2), " bindprivs.conf "(5), " rmmod "(8)"
